export type { TileStatus as LetterStatus } from '@/types/game';
export { getDailyWord, isValidWord, evaluateGuess } from '@/lib/gameLogic';

// DAILY_WORDS: ~365 common, recognizable 5-letter words used as daily answers.
// Every word here must also appear in VALID_WORDS.
export const DAILY_WORDS: string[] = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult',
  'after', 'again', 'agent', 'agree', 'ahead', 'alarm', 'album', 'alert',
  'alien', 'align', 'alive', 'allow', 'alone', 'along', 'alter', 'angel',
  'anger', 'angle', 'angry', 'ankle', 'apple', 'arena', 'argue', 'arise',
  'armor', 'aside', 'atlas', 'avoid', 'awake', 'award', 'aware', 'baker',
  'basic', 'basin', 'batch', 'beach', 'begin', 'being', 'below', 'bench',
  'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blaze', 'bleed',
  'blend', 'blind', 'block', 'blood', 'bloom', 'board', 'bonus', 'boost',
  'bound', 'brain', 'brand', 'brave', 'bread', 'break', 'breed', 'brick',
  'bride', 'brief', 'bring', 'broad', 'brush', 'build', 'burst', 'buyer',
  'cabin', 'cable', 'candy', 'cargo', 'carry', 'catch', 'cause', 'chain',
  'chair', 'chalk', 'chaos', 'charm', 'chase', 'cheap', 'check', 'cheek',
  'cheer', 'chess', 'chest', 'chief', 'child', 'chill', 'chunk', 'civic',
  'civil', 'claim', 'clash', 'class', 'clean', 'clear', 'clerk', 'click',
  'cliff', 'climb', 'clock', 'clone', 'close', 'cloth', 'cloud', 'coach',
  'coast', 'count', 'court', 'cover', 'crack', 'craft', 'crane', 'crash',
  'crazy', 'cream', 'crisp', 'cross', 'crowd', 'crown', 'crush', 'curve',
  'cycle', 'daily', 'dance', 'decay', 'delay', 'demon', 'dense', 'depth',
  'devil', 'dirty', 'dodge', 'doubt', 'dough', 'draft', 'drain', 'drama',
  'dream', 'dress', 'drift', 'drill', 'drink', 'drive', 'drown', 'dying',
  'eager', 'eagle', 'early', 'earth', 'eight', 'elect', 'elite', 'ember',
  'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event',
  'every', 'exact', 'exist', 'extra', 'faith', 'false', 'fancy', 'fatal',
  'fault', 'feast', 'fence', 'fever', 'fiber', 'field', 'fight', 'final',
  'first', 'fixed', 'flame', 'flash', 'fleet', 'flesh', 'float', 'flood',
  'floor', 'flour', 'fluid', 'flute', 'focus', 'force', 'forge', 'forth',
  'forum', 'found', 'frame', 'fraud', 'fresh', 'front', 'frost', 'fruit',
  'funny', 'giant', 'given', 'glass', 'globe', 'glory', 'glove', 'going',
  'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'grasp', 'grass',
  'grave', 'great', 'green', 'greet', 'grief', 'grind', 'gross', 'group',
  'guard', 'guess', 'guest', 'guide', 'guilt', 'happy', 'harsh', 'haven',
  'heart', 'heavy', 'honor', 'horse', 'hotel', 'house', 'human', 'humor',
  'hurry', 'ideal', 'image', 'imply', 'index', 'inner', 'input', 'issue',
  'jewel', 'joint', 'judge', 'juice', 'knife', 'knock', 'label', 'large',
  'laser', 'later', 'laugh', 'layer', 'learn', 'lease', 'leave', 'legal',
  'lemon', 'level', 'light', 'limit', 'linen', 'liver', 'local', 'logic',
  'loose', 'lover', 'lower', 'lucky', 'lunch', 'lying', 'magic', 'major',
  'maker', 'manor', 'maple', 'march', 'match', 'mayor', 'media', 'mercy',
  'merit', 'metal', 'meter', 'might', 'minor', 'mixed', 'model', 'money',
  'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music',
  'nerve', 'never', 'noble', 'noise', 'north', 'noted', 'novel', 'nurse',
  'ocean', 'offer', 'often', 'olive', 'onset', 'opera', 'orbit', 'order',
  'other', 'outer', 'owner', 'panel', 'panic', 'paper', 'party', 'paste',
  'patch', 'pause', 'peace', 'peach', 'pearl', 'penny', 'phase', 'phone',
  'photo', 'piano', 'piece', 'pilot', 'pitch', 'pixel', 'pizza', 'place',
  'plain', 'plane', 'plant', 'plate', 'plaza', 'point', 'polar', 'pound',
  'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize',
  'proof', 'proud', 'prove', 'pulse', 'punch', 'queen', 'quest', 'quick',
  'quiet', 'quite', 'quote', 'radar', 'radio', 'raise', 'rally', 'ranch',
  'range', 'rapid', 'ratio', 'reach', 'react', 'ready', 'realm', 'rebel',
  'reign', 'relax', 'reply', 'rider', 'ridge', 'rifle', 'right', 'rigid',
  'rival', 'river', 'roast', 'robot', 'rocky', 'rough', 'round', 'route',
  'royal', 'ruler', 'rural', 'saint', 'salad', 'scale', 'scene', 'scope',
  'score', 'scout', 'sense', 'serve', 'seven', 'shall', 'shame', 'shape',
  'share', 'sharp', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock',
  'shoot', 'short', 'shout', 'sight', 'since', 'sixth', 'sixty', 'skill',
  'skull', 'sleep', 'slice', 'slide', 'slope', 'smart', 'smell', 'smile',
  'smoke', 'snake', 'solar', 'solid', 'solve', 'sorry', 'sound', 'south',
  'space', 'spare', 'spark', 'speak', 'speed', 'spend', 'spice', 'spine',
  'split', 'spoke', 'spoon', 'sport', 'spray', 'squad', 'stack', 'staff',
  'stage', 'stain', 'stake', 'stale', 'stall', 'stamp', 'stand', 'stark',
  'start', 'state', 'steak', 'steal', 'steam', 'steel', 'steep', 'steer',
  'stern', 'stick', 'still', 'stock', 'stone', 'store', 'storm', 'story',
  'stove', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite',
  'sunny', 'super', 'swamp', 'swear', 'sweep', 'sweet', 'swift', 'swing',
  'sword', 'taste', 'teach', 'teeth', 'thank', 'theft', 'theme', 'there',
  'thick', 'thief', 'thing', 'think', 'third', 'those', 'three', 'threw',
  'throw', 'thumb', 'tiger', 'tight', 'timer', 'tired', 'title', 'today',
  'token', 'total', 'touch', 'tough', 'tower', 'toxic', 'trace', 'track',
  'trade', 'trail', 'train', 'trait', 'trash', 'treat', 'trend', 'trial',
  'tribe', 'trick', 'tried', 'troop', 'truck', 'truly', 'trunk', 'trust',
  'truth', 'twist', 'ultra', 'uncle', 'under', 'union', 'unite', 'unity',
  'until', 'upper', 'upset', 'urban', 'usual', 'valid', 'value', 'vault',
  'venue', 'verse', 'video', 'vigor', 'vinyl', 'viral', 'virus', 'visit',
  'vital', 'vivid', 'vocal', 'voice', 'voter', 'wages', 'waste', 'watch',
  'water', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole',
  'whose', 'woman', 'world', 'worry', 'worse', 'worst', 'worth', 'would',
  'wound', 'wrath', 'write', 'wrong', 'wrote', 'yacht', 'yield', 'young',
  'youth', 'zebra',
];

// VALID_WORDS: 2,000+ common 5-letter English words for guess validation.
// Includes all DAILY_WORDS plus additional valid guesses.
export const VALID_WORDS: string[] = [
  // A
  'aback', 'abate', 'abbey', 'abbot', 'abhor', 'abide', 'abort', 'about',
  'above', 'abuse', 'abyss', 'acorn', 'acres', 'acted', 'actin', 'actor',
  'acute', 'adage', 'added', 'adder', 'adept', 'admit', 'adobe', 'adopt',
  'adore', 'adorn', 'adult', 'aegis', 'aeons', 'afoot', 'after', 'again',
  'agent', 'aging', 'agile', 'agony', 'agree', 'ahead', 'aided', 'aimed',
  'aisle', 'alarm', 'album', 'alder', 'alert', 'algae', 'alibi', 'alien',
  'align', 'alike', 'alive', 'allay', 'alley', 'allot', 'allow', 'alloy',
  'aloft', 'alone', 'along', 'aloof', 'alpha', 'altar', 'alter', 'amber',
  'amble', 'amend', 'amine', 'amino', 'amiss', 'ample', 'amuse', 'angel',
  'anger', 'angle', 'angry', 'anime', 'ankle', 'annex', 'annoy', 'antic',
  'anvil', 'aorta', 'apart', 'aphid', 'apple', 'apply', 'apron', 'arbor',
  'arena', 'argue', 'arise', 'armor', 'aroma', 'arose', 'array', 'arrow',
  'arson', 'aside', 'asked', 'asset', 'atlas', 'atone', 'attic', 'audio',
  'audit', 'aught', 'augur', 'aunts', 'avail', 'avert', 'avian', 'avoid',
  'await', 'awake', 'award', 'aware', 'awful', 'awoke', 'axial', 'axiom',
  'azure',
  // B
  'badge', 'badly', 'bagel', 'baggy', 'baked', 'baker', 'baldy', 'balks',
  'balls', 'balms', 'balmy', 'banal', 'bands', 'banes', 'bangs', 'banjo',
  'banks', 'barbs', 'bards', 'bared', 'barge', 'barks', 'barns', 'baron',
  'basal', 'based', 'basic', 'basil', 'basin', 'basis', 'batch', 'baths',
  'baton', 'beach', 'beads', 'beady', 'beaks', 'beams', 'beans', 'beard',
  'bears', 'beast', 'beats', 'beech', 'beefs', 'beefy', 'beeps', 'beers',
  'begin', 'begun', 'being', 'bells', 'belly', 'below', 'belts', 'bench',
  'bends', 'berry', 'berth', 'bible', 'bikes', 'bills', 'bingo', 'biome',
  'birch', 'birds', 'birth', 'bites', 'black', 'blade', 'blame', 'bland',
  'blank', 'blare', 'blast', 'blaze', 'bleak', 'bleat', 'bleed', 'blend',
  'bless', 'blimp', 'blind', 'bliss', 'blitz', 'bloat', 'blobs', 'block',
  'bloke', 'blond', 'blood', 'bloom', 'blown', 'blows', 'bluff', 'blunt',
  'blurt', 'blush', 'board', 'boast', 'boats', 'bolts', 'bombs', 'bonds',
  'bones', 'bonus', 'books', 'boost', 'booth', 'boots', 'booty', 'borax',
  'bored', 'borne', 'bosom', 'bossy', 'botch', 'bound', 'boxer', 'brace',
  'braid', 'brain', 'brake', 'brand', 'brash', 'brass', 'brave', 'bravo',
  'brawl', 'brawn', 'bread', 'break', 'breed', 'brick', 'bride', 'brief',
  'brine', 'bring', 'brink', 'brisk', 'broad', 'broil', 'broke', 'brood',
  'brook', 'broom', 'broth', 'brown', 'brush', 'brute', 'buddy', 'budge',
  'buggy', 'build', 'built', 'bulge', 'bulky', 'bulls', 'bully', 'bumps',
  'bumpy', 'bunch', 'bunks', 'bunny', 'burns', 'burnt', 'burst', 'bushy',
  'busty', 'buyer', 'bytes',
  // C
  'cabal', 'cabin', 'cable', 'cadet', 'cadre', 'cafes', 'caged', 'cages',
  'cairn', 'cakes', 'calls', 'calms', 'camel', 'camps', 'canal', 'candy',
  'canes', 'canon', 'canoe', 'caper', 'cards', 'cargo', 'cared', 'cares',
  'carol', 'carry', 'carve', 'cases', 'catch', 'cater', 'cause', 'caves',
  'cease', 'cedar', 'chain', 'chair', 'chalk', 'champ', 'chant', 'chaos',
  'charm', 'chart', 'chase', 'cheap', 'cheat', 'check', 'cheek', 'cheer',
  'chess', 'chest', 'chick', 'chief', 'child', 'chill', 'chime', 'china',
  'chips', 'choir', 'chord', 'chore', 'chose', 'chunk', 'churn', 'cider',
  'cigar', 'cinch', 'circa', 'cited', 'civic', 'civil', 'claim', 'clamp',
  'clams', 'clang', 'clank', 'claps', 'clash', 'clasp', 'class', 'claws',
  'clean', 'clear', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clips',
  'cloak', 'clock', 'clone', 'close', 'cloth', 'cloud', 'clout', 'clown',
  'clubs', 'cluck', 'clued', 'clues', 'clump', 'clung', 'coach', 'coals',
  'coast', 'coats', 'cobra', 'cocoa', 'coded', 'codes', 'coils', 'coins',
  'color', 'comet', 'comic', 'comma', 'coned', 'cones', 'copse', 'coral',
  'cords', 'cores', 'corny', 'couch', 'cough', 'could', 'count', 'coupe',
  'coups', 'court', 'cover', 'covet', 'crack', 'craft', 'cramp', 'crane',
  'crash', 'crate', 'crave', 'crawl', 'craze', 'crazy', 'creak', 'cream',
  'creed', 'creek', 'creep', 'crest', 'crews', 'cribs', 'cried', 'cries',
  'crime', 'crisp', 'croak', 'crock', 'crook', 'crops', 'cross', 'crowd',
  'crown', 'crude', 'cruel', 'crush', 'crust', 'cubic', 'cupid', 'curds',
  'cured', 'curls', 'curly', 'curry', 'curse', 'curve', 'cycle',
  // D
  'daily', 'dairy', 'daisy', 'dance', 'dared', 'dated', 'dates', 'datum',
  'deals', 'dealt', 'death', 'debit', 'debut', 'decay', 'decks', 'decor',
  'decoy', 'decry', 'deeds', 'deity', 'delay', 'delta', 'delve', 'demon',
  'denim', 'dense', 'depot', 'depth', 'derby', 'desks', 'deter', 'detox',
  'deuce', 'devil', 'diary', 'diets', 'digit', 'dimly', 'dined', 'diner',
  'dirty', 'disco', 'ditch', 'ditto', 'dizzy', 'docks', 'dodge', 'doing',
  'dolls', 'donor', 'donut', 'doors', 'doses', 'doubt', 'dough', 'downs',
  'draft', 'drain', 'drake', 'drama', 'drank', 'drape', 'drawn', 'draws',
  'dread', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive',
  'drone', 'drool', 'drops', 'drown', 'drugs', 'drums', 'drunk', 'dryer',
  'dryly', 'ducks', 'duels', 'dully', 'dumps', 'dunce', 'dunes', 'dunks',
  'duple', 'dusty', 'dwarf', 'dwell', 'dying',
  // E
  'eager', 'eagle', 'early', 'earth', 'eased', 'easel', 'eaten', 'eater',
  'edges', 'edged', 'edict', 'eight', 'elbow', 'elder', 'elect', 'elite',
  'elope', 'elude', 'ember', 'emoji', 'empty', 'ended', 'enemy', 'enjoy',
  'enact', 'ensue', 'enter', 'entry', 'envoy', 'epoch', 'equal', 'equip',
  'erase', 'erode', 'error', 'erupt', 'essay', 'ethic', 'evade', 'event',
  'every', 'evict', 'evoke', 'exact', 'exalt', 'exams', 'excel', 'exert',
  'exile', 'exist', 'expel', 'extra', 'exude',
  // F
  'fable', 'faced', 'faces', 'facet', 'facts', 'faded', 'fails', 'faint',
  'fairy', 'faith', 'falls', 'false', 'famed', 'fancy', 'fangs', 'farce',
  'farms', 'fatal', 'fatty', 'fault', 'fauna', 'favor', 'feast', 'feats',
  'feeds', 'feels', 'feign', 'fence', 'fends', 'ferns', 'ferry', 'fetch',
  'fever', 'fewer', 'fiber', 'field', 'fiend', 'fiery', 'fifth', 'fifty',
  'fight', 'filed', 'files', 'filet', 'fills', 'films', 'filth', 'final',
  'finch', 'finds', 'fined', 'finer', 'fires', 'first', 'fishy', 'fixed',
  'fixer', 'flags', 'flair', 'flake', 'flaky', 'flame', 'flank', 'flaps',
  'flare', 'flash', 'flask', 'flats', 'flaws', 'fleas', 'fleck', 'flesh',
  'fleet', 'flick', 'flier', 'flies', 'fling', 'flint', 'flips', 'flirt',
  'float', 'flock', 'flood', 'floor', 'flops', 'flora', 'flour', 'flows',
  'fluid', 'fluke', 'flung', 'flush', 'flute', 'foams', 'focal', 'focus',
  'foggy', 'foils', 'folks', 'folly', 'fonts', 'foods', 'fools', 'foray',
  'force', 'forge', 'forms', 'forte', 'forth', 'forty', 'forum', 'found',
  'foxes', 'foyer', 'frame', 'frank', 'fraud', 'freak', 'freed', 'fresh',
  'friar', 'fried', 'fries', 'frisk', 'frock', 'frogs', 'front', 'frost',
  'frown', 'froze', 'fruit', 'fryer', 'fuels', 'fully', 'fumes', 'funds',
  'fungi', 'funky', 'funny', 'furry', 'fuses', 'fussy', 'fuzzy',
  // G
  'gaily', 'gains', 'gamer', 'games', 'gangs', 'gaped', 'gases', 'gates',
  'gauge', 'gaunt', 'gauze', 'gazer', 'gears', 'geeks', 'genes', 'genre',
  'gents', 'genus', 'germs', 'ghost', 'giant', 'gifts', 'giddy', 'girls',
  'given', 'gives', 'gland', 'glare', 'glass', 'glaze', 'gleam', 'glide',
  'glimp', 'glint', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'glows',
  'glued', 'glues', 'gnome', 'goats', 'godly', 'going', 'golfs', 'goner',
  'goods', 'goose', 'gorge', 'gowns', 'grace', 'grade', 'graft', 'grain',
  'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grate', 'grave',
  'gravy', 'graze', 'great', 'greed', 'green', 'greet', 'grief', 'grill',
  'grind', 'grins', 'gripe', 'grips', 'groan', 'groin', 'groom', 'grope',
  'gross', 'group', 'grove', 'growl', 'grown', 'grows', 'gruel', 'gruff',
  'grunt', 'guard', 'guess', 'guest', 'guide', 'guild', 'guilt', 'guise',
  'gulch', 'gulls', 'gulps', 'gummy', 'gusts', 'gusty', 'gypsy',
  // H
  'habit', 'hacky', 'halls', 'halts', 'hands', 'handy', 'hangs', 'happy',
  'hardy', 'harms', 'harps', 'harsh', 'haste', 'hasty', 'hatch', 'hated',
  'hates', 'hauls', 'haunt', 'haven', 'havoc', 'hawks', 'hazel', 'heads',
  'heady', 'heals', 'heard', 'heart', 'heats', 'heavy', 'hedge', 'heeds',
  'heels', 'hefty', 'heist', 'hello', 'helps', 'hence', 'herbs', 'herds',
  'heron', 'hills', 'hilly', 'hinge', 'hints', 'hippo', 'hired', 'hitch',
  'hobby', 'hoist', 'holds', 'holes', 'holly', 'homer', 'homes', 'honey',
  'honor', 'hooks', 'hoped', 'hopes', 'horns', 'horse', 'hosts', 'hotel',
  'hound', 'house', 'hover', 'howls', 'human', 'humid', 'humor', 'humps',
  'hurry', 'husks', 'husky', 'hyena', 'hymns', 'hyper',
  // I
  'icing', 'icons', 'ideal', 'ideas', 'idled', 'idols', 'image', 'imply',
  'inbox', 'incur', 'index', 'indie', 'inert', 'infer', 'ingot', 'inner',
  'input', 'intro', 'ionic', 'irate', 'irony', 'issue', 'ivory', 'ivied',
  // J
  'jaded', 'jails', 'jaunt', 'jazzy', 'jeans', 'jelly', 'jerks', 'jerky',
  'jewel', 'jiffy', 'jinks', 'joeys', 'joker', 'jokes', 'jolly', 'jolts',
  'joint', 'joust', 'judge', 'juice', 'juicy', 'jumbo', 'jumps', 'jumpy',
  'juror', 'junky',
  // K
  'kayak', 'kebab', 'keels', 'keeps', 'ketch', 'kicks', 'kills', 'kinds',
  'kings', 'kiosk', 'kites', 'knack', 'knead', 'kneel', 'knees', 'knelt',
  'knife', 'knits', 'knobs', 'knock', 'knoll', 'knots', 'known',
  'knows', 'knurl', 'koala',
  // L
  'label', 'labor', 'laced', 'laces', 'lacks', 'laden', 'ladle', 'lakes',
  'lambs', 'lamps', 'lance', 'lands', 'lanes', 'lapse', 'large', 'larva',
  'laser', 'lasts', 'latch', 'later', 'latex', 'lathe', 'lauds', 'laugh',
  'layer', 'leads', 'leafy', 'leaks', 'leaky', 'leaps', 'leapt', 'learn',
  'lease', 'leash', 'least', 'leave', 'ledge', 'lefts', 'legal', 'lemma',
  'lemon', 'lends', 'level', 'lever', 'light', 'liked', 'liken', 'lilac',
  'limbs', 'limes', 'limit', 'limps', 'lined', 'linen', 'liner', 'lines',
  'lingo', 'links', 'lions', 'lists', 'liter', 'lived', 'liven', 'liver',
  'lives', 'llama', 'loads', 'loafs', 'loans', 'lobby', 'local', 'locks',
  'locus', 'lodge', 'lofty', 'logic', 'logos', 'looks', 'looms', 'loops',
  'loose', 'lords', 'lorry', 'loser', 'loses', 'lotus', 'lousy', 'lover',
  'loved', 'lower', 'loyal', 'lucid', 'lucky', 'lulls', 'lumps', 'lumpy',
  'lunch', 'lunge', 'lungs', 'lured', 'lurks', 'lusty', 'lying', 'lymph',
  'lyric',
  // M
  'macho', 'macro', 'magic', 'magma', 'major', 'maker', 'males', 'mango',
  'mania', 'manic', 'manor', 'maple', 'march', 'marks', 'marsh', 'masks',
  'mason', 'match', 'mates', 'maths', 'mayor', 'meals', 'means', 'meats',
  'meaty', 'medal', 'media', 'melee', 'melon', 'melts', 'mercy', 'merge',
  'merit', 'merry', 'messy', 'metal', 'meter', 'micro', 'midst', 'might',
  'milks', 'milky', 'mills', 'mimic', 'minds', 'mined', 'miner', 'mines',
  'minor', 'minus', 'mirth', 'miser', 'misty', 'miter', 'mixed', 'mixer',
  'mixes', 'moans', 'moats', 'mocks', 'model', 'modem', 'modes', 'moist',
  'molar', 'molds', 'moldy', 'money', 'monks', 'month', 'moods', 'moody',
  'moose', 'moral', 'morph', 'mossy', 'motel', 'moths', 'motor', 'motto',
  'mound', 'mount', 'mourn', 'mouse', 'mouth', 'moved', 'mover', 'moves',
  'movie', 'mowed', 'mucky', 'muddy', 'mules', 'multi', 'mummy', 'mural',
  'murky', 'music', 'musty', 'muted', 'myths',
  // N
  'nails', 'naive', 'named', 'nanny', 'napes', 'nasty', 'naval', 'navel',
  'needs', 'nerve', 'nervy', 'nests', 'never', 'newer', 'newly', 'niche',
  'night', 'nimby', 'ninja', 'noble', 'nobly', 'noise', 'noisy', 'nomad',
  'norms', 'north', 'noted', 'notes', 'novel', 'nudge', 'nurse', 'nylon',
  'nymph',
  // O
  'oaken', 'oasis', 'oaths', 'occur', 'ocean', 'oddly', 'odors', 'offer',
  'often', 'oiled', 'olive', 'omega', 'onset', 'oomph', 'opens', 'opera',
  'opted', 'optic', 'orbit', 'order', 'organ', 'other', 'ought', 'ounce',
  'outer', 'outdo', 'ovals', 'ovens', 'overt', 'owned', 'owner', 'oxide',
  'ozone',
  // P
  'paced', 'paces', 'packs', 'paddy', 'pages', 'pains', 'paint', 'pairs',
  'palms', 'palsy', 'panda', 'panel', 'panes', 'panic', 'pants', 'paper',
  'parks', 'parse', 'parts', 'party', 'paste', 'pasty', 'patch', 'paths',
  'patio', 'pause', 'paved', 'paves', 'pawns', 'peace', 'peach', 'peaks',
  'pearl', 'pears', 'pease', 'pecan', 'pedal', 'peels', 'penny', 'perch',
  'perks', 'perky', 'perms', 'pesky', 'pests', 'petal', 'petty', 'phase',
  'phone', 'photo', 'piano', 'picks', 'picky', 'piece', 'piled', 'piles',
  'pills', 'pilot', 'pinch', 'pines', 'pinky', 'pints', 'pious', 'pipes',
  'pitch', 'pitts', 'pivot', 'pixel', 'pizza', 'place', 'plaid', 'plain',
  'plane', 'plank', 'plans', 'plant', 'plate', 'plays', 'plaza', 'plead',
  'pleas', 'pleat', 'plied', 'plier', 'plods', 'plots', 'plows', 'ploys',
  'pluck', 'plugs', 'plumb', 'plume', 'plump', 'plums', 'plunk', 'plush',
  'pluto', 'poach', 'poems', 'poets', 'point', 'poise', 'poker',
  'polar', 'poles', 'polls', 'polyp', 'ponds', 'pools', 'porch', 'pores',
  'ports', 'posed', 'poses', 'posse', 'posts', 'pouch', 'pound', 'pours',
  'power', 'prank', 'prawn', 'prays', 'press', 'price', 'prick', 'pride',
  'pried', 'prime', 'print', 'prior', 'prism', 'privy', 'prize', 'probe',
  'prods', 'prone', 'prong', 'proof', 'props', 'prose', 'proud', 'prove',
  'prowl', 'prude', 'prune', 'psalm', 'pulls', 'pulps', 'pulse', 'pumps',
  'punch', 'pupil', 'puppy', 'purge', 'purse', 'pushy', 'putts', 'pygmy',
  // Q
  'quack', 'quail', 'qualm', 'quart', 'quasi', 'queen', 'query', 'quest',
  'queue', 'quick', 'quiet', 'quill', 'quilt', 'quirk', 'quite', 'quota',
  'quote',
  // R
  'races', 'racks', 'radar', 'radii', 'radio', 'raids', 'rails', 'rains',
  'rainy', 'raise', 'rally', 'ramps', 'ranch', 'range', 'ranks', 'rapid',
  'rarer', 'rated', 'rates', 'ratio', 'razor', 'reach', 'react',
  'reads', 'ready', 'realm', 'reaps', 'rebel', 'rebus', 'recon', 'reeds',
  'reefs', 'reels', 'reign', 'reins', 'relax', 'relay', 'relic', 'remit',
  'renal', 'renew', 'rents', 'repay', 'repel', 'reply', 'reset', 'resin',
  'retro', 'rider', 'rides', 'ridge', 'rifle', 'right', 'rigid', 'rings',
  'rinse', 'ripen', 'risen', 'rises', 'risky', 'rival', 'river', 'rivet',
  'roads', 'roams', 'roars', 'roast', 'robes', 'robin', 'robot', 'rocks',
  'rocky', 'rogue', 'roles', 'rolls', 'roman', 'roofs', 'rooms', 'roomy',
  'roots', 'roped', 'ropes', 'roses', 'rouge', 'rough', 'round', 'route',
  'rover', 'rowdy', 'royal', 'rugby', 'ruins', 'ruled', 'ruler', 'rules',
  'rumor', 'rungs', 'rural', 'rusty',
  // S
  'sadly', 'safer', 'sails', 'saint', 'salad', 'sales', 'salon',
  'salsa', 'salts', 'salty', 'salve', 'sands', 'sandy', 'saner', 'satin',
  'sauce', 'saucy', 'sauna', 'saved', 'saves', 'savor', 'scale', 'scalp',
  'scams', 'scans', 'scare', 'scarf', 'scary', 'scene', 'scent', 'scope',
  'score', 'scorn', 'scout', 'scowl', 'scram', 'scrap', 'seals', 'seams',
  'seats', 'seeds', 'seedy', 'seeks', 'seize', 'sense', 'sepia', 'serve',
  'setup', 'seven', 'sever', 'shade', 'shady', 'shaft', 'shake', 'shaky',
  'shall', 'shame', 'shape', 'shard', 'share', 'shark', 'sharp', 'shave',
  'shawl', 'shear', 'sheds', 'sheen', 'sheep', 'sheer', 'sheet', 'shelf',
  'shell', 'shift', 'shims', 'shine', 'shiny', 'ships', 'shirt', 'shock',
  'shoes', 'shone', 'shook', 'shoot', 'shops', 'shore', 'short', 'shout',
  'shove', 'shown', 'shows', 'shrub', 'shrug', 'shuts', 'sided', 'sides',
  'siege', 'sieve', 'sight', 'sigma', 'signs', 'silks', 'silky', 'silly',
  'since', 'siren', 'sites', 'sixth', 'sixty', 'sized', 'sizes', 'skate',
  'skids', 'skill', 'skimp', 'skips', 'skirt', 'skull', 'slabs', 'slain',
  'slant', 'slaps', 'slash', 'slate', 'slave', 'slays', 'sleep', 'sleet',
  'slept', 'slice', 'slide', 'slime', 'slimy', 'sling', 'slink', 'slope',
  'slots', 'slows', 'slump', 'slung', 'slurp', 'small', 'smart', 'smash',
  'smear', 'smell', 'smelt', 'smile', 'smirk', 'smith', 'smoke', 'smoky',
  'snack', 'snail', 'snake', 'snaps', 'snare', 'snarl', 'sneak', 'sneer',
  'sniff', 'snore', 'snout', 'snowy', 'soapy', 'soars', 'sober', 'socks',
  'sofas', 'softy', 'soggy', 'soils', 'solar', 'solid', 'solve',
  'songs', 'sonic', 'sorry', 'sorts', 'souls', 'sound', 'south', 'space',
  'spade', 'spans', 'spare', 'spark', 'spawn', 'speak', 'spear', 'speck',
  'specs', 'speed', 'spell', 'spend', 'spent', 'spice', 'spicy', 'spied',
  'spies', 'spill', 'spine', 'spite', 'split', 'spoke', 'spoof', 'spook',
  'spoon', 'sport', 'spots', 'spray', 'spree', 'sprig', 'spurs', 'squad',
  'squat', 'squid', 'stack', 'staff', 'stage', 'stags', 'staid', 'stain',
  'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'stank',
  'stark', 'stars', 'start', 'stash', 'state', 'stays', 'steak', 'steal',
  'steam', 'steel', 'steep', 'steer', 'stems', 'steps', 'stern', 'stews',
  'stick', 'stiff', 'still', 'sting', 'stink', 'stint', 'stirs', 'stock',
  'stoke', 'stole', 'stone', 'stood', 'stool', 'stoop', 'stops', 'store',
  'stork', 'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'stray',
  'strip', 'strut', 'stuck', 'studs', 'study', 'stuff', 'stump', 'stung',
  'stunk', 'stunt', 'style', 'suave', 'sugar', 'suite', 'suits', 'sulky',
  'sunny', 'super', 'surge', 'sushi', 'swamp', 'swans', 'swaps', 'swarm',
  'swath', 'swear', 'sweat', 'sweep', 'sweet', 'swept', 'swift', 'swill',
  'swine', 'swing', 'swipe', 'swirl', 'sword', 'swore', 'sworn', 'swung',
  'syrup',
  // T
  'table', 'tacit', 'tacks', 'tacky', 'taint', 'taken', 'takes', 'tales',
  'talks', 'tamed', 'tango', 'tanks', 'tapes', 'tardy', 'taste', 'tasty',
  'taunt', 'taxes', 'teach', 'teams', 'tears', 'teary', 'tease', 'teddy',
  'teens', 'teeth', 'tempo', 'tends', 'tense', 'tenth', 'tents', 'terms',
  'tests', 'thank', 'theft', 'theme', 'there', 'thick', 'thief', 'thigh',
  'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw', 'throw',
  'thuds', 'thugs', 'thumb', 'tidal', 'tiers', 'tiger', 'tight', 'tiles',
  'tilts', 'timer', 'times', 'timid', 'tints', 'tipsy', 'tired', 'titan',
  'title', 'toast', 'today', 'token', 'tolls', 'tombs', 'toned', 'tones',
  'tongs', 'tools', 'tooth', 'topaz', 'topic', 'torch', 'total', 'totem',
  'touch', 'tough', 'tours', 'towel', 'tower', 'towns', 'toxic', 'trace',
  'track', 'tract', 'trade', 'trail', 'train', 'trait', 'tramp', 'traps',
  'trash', 'trawl', 'treat', 'trees', 'trend', 'trial', 'tribe', 'trick',
  'tried', 'tries', 'trims', 'trips', 'trite', 'troll', 'troop', 'troth',
  'trots', 'trout', 'truce', 'truck', 'truly', 'trump', 'trunk', 'truss',
  'trust', 'truth', 'tuber', 'tucks', 'tulip', 'tumor', 'tuned', 'tunes',
  'turbo', 'turns', 'tutor', 'tweak', 'tweed', 'tweet', 'twice', 'twigs',
  'twine', 'twins', 'twirl', 'twist', 'tykes', 'typed', 'types',
  // U
  'udder', 'ulcer', 'ultra', 'umbra', 'uncle', 'uncut', 'under', 'undid',
  'undue', 'unfit', 'union', 'unite', 'units', 'unity', 'unlit', 'until',
  'upper', 'upset', 'urban', 'urged', 'usher', 'using', 'usual', 'utter',
  // V
  'vague', 'valid', 'value', 'valve', 'vapor', 'vault', 'veils', 'veins',
  'veldt', 'venue', 'verbs', 'verge', 'verse', 'video', 'views', 'vigor',
  'vines', 'vinyl', 'viola', 'viper', 'viral', 'virus', 'visit', 'visor',
  'vista', 'vital', 'vivid', 'vixen', 'vocal', 'vodka', 'vogue', 'voice',
  'voter', 'vouch', 'vowed', 'vowel', 'vulva',
  // W
  'waded', 'wader', 'waged', 'wager', 'wages', 'wagon', 'waist', 'walks',
  'walls', 'waltz', 'wands', 'wants', 'wards', 'warns', 'warps', 'warts',
  'waste', 'watch', 'water', 'watts', 'waved', 'waver', 'waves', 'waxed',
  'weary', 'weave', 'wedge', 'weeds', 'weedy', 'weeks', 'weigh', 'weird',
  'wells', 'welsh', 'wheat', 'wheel', 'where', 'which', 'while', 'whims',
  'whine', 'whips', 'whirl', 'white', 'whole', 'whose', 'wicks', 'wider',
  'width', 'wield', 'wills', 'wimpy', 'winds', 'windy', 'wines', 'wings',
  'winks', 'wiped', 'wiper', 'wired', 'wires', 'witch', 'woman', 'women',
  'woods', 'woody', 'words', 'wordy', 'works', 'world', 'worms', 'worry',
  'worse', 'worst', 'worth', 'would', 'wound', 'wrath', 'wreak', 'wreck',
  'wrist', 'write', 'wrong', 'wrote', 'wryly',
  // X
  'xenon',
  // Y
  'yacht', 'yards', 'yarns', 'years', 'yeast', 'yield', 'young', 'yours',
  'youth',
  // Z
  'zappy', 'zebra', 'zeros', 'zesty', 'zilch', 'zincs', 'zoned', 'zones',
];
